name: CI
on:
  push:
    branches: [main]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 7.2.1
      - name: Install modules
        run: pnpm install

      - name: Run Lint
        run: pnpm run docs:build
        
      - name: Deploy
        uses: peaceiris/actions-docs@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/.vitepress/dist
